version: "3"
services:

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    volumes:
      - mysql_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: mediscreen
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - mediscreen-network
    cap_add:
      - SYS_NICE

  mongo_db:
      image: mongo:latest
      container_name: mongo_db
      volumes:
        - mongo_db_data:/data/db
        - mongo_config:/data/configdb
      restart: always
      ports:
        - "27017:27017"
      networks:
       - mediscreen-network

  mediscreen:
    depends_on:
      - patientinfos
      - practitionnernote
      - risk
    image: mediscreen
    container_name: mediscreen
    ports:
      - "8080:8080"
    restart: always
    environment:
      PATIENT_INFO_PROXY_URL: http://patientinfos:8081
      PRACTITIONNER_NOTE_PROXY_URL: http://practitionnernotes:8082
      RISK_PROXY_URL: http://risks:8083
    networks:
      - mediscreen-network

  patientinfos:
    image: patientinfos
    container_name: patientinfos
    depends_on:
      - mysql_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db/mediscreen
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8081:8081"
    restart: always
    networks:
      - mediscreen-network

  practitionnernote:
    image: practitionnernote
    container_name: practitionnernote
    depends_on:
      - mongo_db
    environment:
      SPRING_DATA_MONGODB_HOST: mongo_db
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: mediscreennotes
    ports:
      - "8082:8082"
    restart: always
    networks:
      - mediscreen-network

  risk:
    image: risk
    container_name: risk
    depends_on:
      - patientinfos
      - practitionnernote
    ports:
      - "8083:8083"
    restart: always
    environment:
      PATIENT_INFO_PROXY_URL: http://patientinfos:8081
      PRACTITIONNER_NOTE_PROXY_URL: http://practitionnernotes:8082
    networks:
      - mediscreen-network   

networks:
  mediscreen-network:
    driver: bridge      

volumes:
  mysql_db_data: 
  mongo_db_data: 
  mongo_config: 